# Generated by Django 6.0.2 on 2026-03-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_parent_transaction_child_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], default='parent', max_length=10),
        ),
    ]
